package com.shiftschedule.app.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import java.util.Locale

val LocalLang = compositionLocalOf { "ru" }

object Strings {
    private val ru = mapOf(
        "tab_calendar" to "Календарь",
        "tab_templates" to "Шаблоны",
        "tab_compare" to "Сравнение",
        "tab_settings" to "Настройки",
        "today" to "Сегодня",
        "no_shift" to "нет смены",
        "hint_calendar" to "Свайп или ‹ › — месяц · нажатие — изменить · долгое нажатие — кто где",
        "tip_calendar" to "Нажми на день, чтобы поставить смену. Долгое нажатие — кто где в этот день. Свайп или стрелки — смена месяца.",
        "tip_templates" to "Зажми карточку и тяни — сортировка. Свайп влево — удаление. Кнопка с двумя квадратами — копия графика.",
        "tip_compare" to "Тап по дню — кто где. ✦ — общий выходной всех графиков. Переключись на «Год» для годового отчёта.",
        "tip_settings" to "Меняйте тему и язык здесь. Экспорт создаёт резервную копию всех графиков — храните файл безопасно.",
        "add_schedule" to "Добавить график",
        "select_schedule" to "Выбрать график",
        "who_where" to "Кто где",
        "close" to "Закрыть",
        "prev_month" to "Предыдущий месяц",
        "next_month" to "Следующий месяц",
        "day_shifts" to "Дневных",
        "night_shifts" to "Ночных",
        "off_days" to "Выходных",
        "edit_day" to "День",
        "schedule_label" to "График",
        "shift_type" to "Тип смены",
        "duration" to "Длительность",
        "days_n" to "%d дн.",
        "after_period" to "После окончания:",
        "continue_pattern" to "Дальше как по графику",
        "shift_cycle" to "Сдвинуть цикл на %d дн.",
        "apply_to" to "Применить к",
        "this_day" to "Только этот день",
        "this_following" to "Этот и последующие",
        "entire_schedule" to "Весь график с этой даты",
        "clear_day" to "Очистить день (вернуть к шаблону)",
        "save" to "Сохранить",
        "cancel" to "Отмена",
        "new_schedule" to "Новый график",
        "edit_schedule" to "Редактировать график",
        "name_label" to "Название",
        "placeholder_name" to "Я, Жена, Петя…",
        "name_error" to "Имя не может состоять из пробелов",
        "color" to "Цвет",
        "template" to "Шаблон",
        "no_template" to "Без шаблона (ручной)",
        "start_date" to "Дата начала",
        "create" to "Создать",
        "new_template" to "Новый шаблон",
        "edit_template" to "Редактировать шаблон",
        "description" to "Описание",
        "add_shifts" to "Добавить смены:",
        "sequence" to "Последовательность (нажатие убирает):",
        "empty_pattern" to "Пусто — добавьте смены кнопками выше",
        "templates_title" to "Графики и шаблоны",
        "search_placeholder" to "Поиск…",
        "search" to "Поиск",
        "clear" to "Очистить",
        "my_schedules" to "Мои графики",
        "built_in" to "Встроенные шаблоны",
        "user_templates" to "Пользовательские шаблоны",
        "no_schedules_yet" to "Нет графиков",
        "create_first" to "Создайте первый график — по шаблону или вручную",
        "no_templates_yet" to "Нет пользовательских шаблонов",
        "create_template" to "Соберите свою последовательность смен",
        "manual" to "Ручной",
        "from" to "с",
        "copy" to "Копировать",
        "edit" to "Редактировать",
        "delete" to "Удалить",
        "copy_created" to "Копия создана",
        "undo" to "Отменить",
        "deleted_schedule" to "Schedule “%s” deleted",
        "delete_schedule_q" to "Удалить график?",
        "delete_schedule_text" to "“%s” will be deleted. You can undo right after.",
        "delete_template_q" to "Удалить шаблон?",
        "template_used" to "Используется в графиках: %d. Они станут ручными.",
        "template_deleted_text" to "Шаблон будет удалён.",
        "compare_title" to "Сравнение",
        "month_view" to "Месяц",
        "year_view" to "Год",
        "no_schedules" to "Нет графиков",
        "create_one" to "Создайте хотя бы один график в календаре",
        "stats" to "Статистика",
        "total_off" to "Выходных",
        "total_day" to "Дневных",
        "total_night" to "Ночных",
        "total_holiday" to "Праздничных",
        "all_working" to "Все на работе",
        "year_total" to "Итог за %d",
        "year_by_schedule" to "По графикам за год",
        "appearance_theme" to "Тема",
        "theme_dark" to "Тёмная",
        "theme_light" to "Светлая",
        "theme_sepia" to "Сепия",
        "theme_midnight" to "Полночь",
        "notifications" to "Уведомления",
        "reminders" to "Напоминания",
        "reminders_desc" to "Сводка смен на завтра",
        "time_dialog_title" to "Время напоминания",
        "time_dialog_hint" to "Формат ЧЧ:ММ, например 08:00 или 19:00",
        "time_label" to "Время (ЧЧ:ММ)",
        "change_time" to "Изменить время",
        "display" to "Отображение",
        "emoji" to "Эмодзи в клетках",
        "emoji_desc" to "Иначе: Д/Н/В/Б/О",
        "week_start" to "Первый день недели",
        "mon" to "Понедельник",
        "sun" to "Воскресенье",
        "data" to "Данные",
        "data_desc" to "Резервная копия графиков и шаблонов в файл JSON",
        "version" to "Версия %s · данные хранятся на устройстве",
        "export" to "Экспорт",
        "import" to "Импорт",
        "exported" to "Данные экспортированы",
        "export_error" to "Ошибка экспорта",
        "imported" to "Импорт выполнен",
        "import_bad" to "Файл не подходит",
        "import_error" to "Ошибка импорта",
        "onb_title" to "Добро пожаловать",
        "onb_sub" to "График работы",
        "onb1" to "Создайте первый график",
        "onb1d" to "Выберите шаблон (2/2, 1/3, 5/2 и др.) или начните с ручного ввода",
        "onb2" to "Добавьте близких",
        "onb2d" to "График жены, мужа, напарника — для поиска общих выходных",
        "onb3" to "Сравнивайте",
        "onb3d" to "Вкладка «Сравнение» покажет, когда у всех выходной ✦",
        "onb_btn" to "Создать первый график",
        "onb_note" to "Все данные хранятся на вашем устройстве",
        "widget_title" to "Смены сегодня"
    )

    private val en = mapOf(
        "tab_calendar" to "Calendar",
        "tab_templates" to "Templates",
        "tab_compare" to "Compare",
        "tab_settings" to "Settings",
        "today" to "Today",
        "no_shift" to "no shift",
        "hint_calendar" to "Swipe or ‹ › — month · tap — edit · long press — who is where",
        "tip_calendar" to "Tap a day to set a shift. Long press — who is where. Swipe or arrows — change month.",
        "tip_templates" to "Long press and drag — reorder. Swipe left — delete. Copy button — duplicate schedule.",
        "tip_compare" to "Tap a day — who is where. ✦ — shared day off for all. Switch to Year for annual report.",
        "tip_settings" to "Change theme and language here. Export creates a backup of all schedules — keep the file safe.",
        "add_schedule" to "Add schedule",
        "select_schedule" to "Select schedule",
        "who_where" to "Who is where",
        "close" to "Close",
        "prev_month" to "Previous month",
        "next_month" to "Next month",
        "day_shifts" to "Day",
        "night_shifts" to "Night",
        "off_days" to "Off",
        "edit_day" to "Day",
        "schedule_label" to "Schedule",
        "shift_type" to "Shift type",
        "duration" to "Duration",
        "days_n" to "%d d.",
        "after_period" to "After period:",
        "continue_pattern" to "Continue with pattern",
        "shift_cycle" to "Shift cycle by %d days",
        "apply_to" to "Apply to",
        "this_day" to "This day only",
        "this_following" to "This day and following",
        "entire_schedule" to "Entire schedule from this date",
        "clear_day" to "Clear day (return to template)",
        "save" to "Save",
        "cancel" to "Cancel",
        "new_schedule" to "New schedule",
        "edit_schedule" to "Edit schedule",
        "name_label" to "Name",
        "placeholder_name" to "Me, Wife, Pete…",
        "name_error" to "Name can't be only spaces",
        "color" to "Color",
        "template" to "Template",
        "no_template" to "No template (manual)",
        "start_date" to "Start date",
        "create" to "Create",
        "new_template" to "New template",
        "edit_template" to "Edit template",
        "description" to "Description",
        "add_shifts" to "Add shifts:",
        "sequence" to "Sequence (tap to remove):",
        "empty_pattern" to "Empty — add shifts with buttons above",
        "templates_title" to "Schedules & Templates",
        "search_placeholder" to "Search…",
        "search" to "Search",
        "clear" to "Clear",
        "my_schedules" to "My schedules",
        "built_in" to "Built-in templates",
        "user_templates" to "User templates",
        "no_schedules_yet" to "No schedules",
        "create_first" to "Create your first schedule — by template or manually",
        "no_templates_yet" to "No user templates",
        "create_template" to "Build your own shift sequence",
        "manual" to "Manual",
        "from" to "from",
        "copy" to "Copy",
        "edit" to "Edit",
        "delete" to "Delete",
        "copy_created" to "Copy created",
        "undo" to "Undo",
        "deleted_schedule" to "Schedule “%s” deleted",
        "delete_schedule_q" to "Delete schedule?",
        "delete_schedule_text" to "“%s” will be deleted. You can undo right after.",
        "delete_template_q" to "Delete template?",
        "template_used" to "Used by %d schedules. They will become manual.",
        "template_deleted_text" to "Template will be deleted.",
        "compare_title" to "Compare",
        "month_view" to "Month",
        "year_view" to "Year",
        "no_schedules" to "No schedules",
        "create_one" to "Create at least one schedule in calendar",
        "stats" to "Statistics",
        "total_off" to "Days off",
        "total_day" to "Day shifts",
        "total_night" to "Night shifts",
        "total_holiday" to "Holidays",
        "all_working" to "All working",
        "year_total" to "Total for %d",
        "year_by_schedule" to "By schedule for the year",
        "appearance_theme" to "Theme",
        "theme_dark" to "Dark",
        "theme_light" to "Light",
        "theme_sepia" to "Sepia",
        "theme_midnight" to "Midnight",
        "notifications" to "Notifications",
        "reminders" to "Reminders",
        "reminders_desc" to "Shift summary for tomorrow",
        "time_dialog_title" to "Reminder time",
        "time_dialog_hint" to "HH:MM format, e.g. 08:00 or 19:00",
        "time_label" to "Time (HH:MM)",
        "change_time" to "Change time",
        "display" to "Display",
        "emoji" to "Emoji in cells",
        "emoji_desc" to "Otherwise: D/N/O/S/V",
        "week_start" to "First day of week",
        "mon" to "Monday",
        "sun" to "Sunday",
        "data" to "Data",
        "data_desc" to "Backup of schedules and templates to a JSON file",
        "version" to "Version %s · data stays on your device",
        "export" to "Export",
        "import" to "Import",
        "exported" to "Data exported",
        "export_error" to "Export failed",
        "imported" to "Import completed",
        "import_bad" to "Unsupported file",
        "import_error" to "Import failed",
        "onb_title" to "Welcome",
        "onb_sub" to "Shift Schedule",
        "onb1" to "Create your first schedule",
        "onb1d" to "Pick a template (2/2, 1/3, 5/2…) or start manually",
        "onb2" to "Add your family",
        "onb2d" to "Spouse or partner schedules to find shared days off",
        "onb3" to "Compare",
        "onb3d" to "The Compare tab shows when everyone is off ✦",
        "onb_btn" to "Create first schedule",
        "onb_note" to "All data stays on your device",
        "widget_title" to "Shifts today"
    )

    fun getSystemLanguage(): String {
        val lang = Locale.getDefault().language
        return if (lang in listOf("ru", "kk", "uk", "be")) "ru" else "en"
    }

    fun raw(lang: String, key: String): String {
        return if (lang == "en") en[key] ?: ru[key] ?: key else ru[key] ?: key
    }
}

@Composable
fun monthLocale(): Locale {
    return if (LocalLang.current == "en") Locale.ENGLISH else Locale("ru")
}

@Composable
fun tr(key: String, vararg args: Any): String {
    val s = Strings.raw(LocalLang.current, key)
    return if (args.isEmpty()) s else s.format(*args)
}