package com.shiftschedule.app.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import java.util.Locale

val LocalLang = compositionLocalOf { "ru" }

object Strings {
    private val ru = mapOf(
        "tab_calendar" to "Календарь",
        "tab_templates" to "Шаблоны",
        "tab_compare" to "Совпадения",
        "tab_settings" to "Настройки",
        "today" to "Сегодня",
        "today_label" to "Сегодня",
        "next_shift" to "Следующая смена",
        "no_shift" to "нет смены",
        "hint_calendar" to "Свайп или ‹ › — месяц · нажатие — изменить · долгое нажатие — кто где",
        "tip_calendar" to "Нажми на день — поставить смену. Долгое нажатие — кто где. Свайп или стрелки — месяц. 🎉 — праздники РФ подсвечиваются автоматически.",
        "tip_templates" to "Зажми карточку и тяни — сортировка. Свайп влево — удаление. Кнопка с двумя квадратами — копия графика.",
        "tip_compare" to "Цвет заливки показывает смены. Контур показывает совпадение: зелёный — день, фиолетовый — ночь, жёлтый — общий выходной. Сутки могут совпадать и с днём, и с ночью.",
        "tip_settings" to "Выберите тему, язык и первый день недели. Настройте уведомления и праздники РФ. Данные можно экспортировать в JSON.",
        "add_schedule" to "Добавить график",
        "select_schedule" to "Выбрать график",
        "who_where" to "Кто где",
        "close" to "Закрыть",
        "prev_month" to "Предыдущий месяц",
        "next_month" to "Следующий месяц",
        "day_shifts" to "Дневных",
        "night_shifts" to "Ночных",
        "off_days" to "Выходных",
        "total_holiday" to "Праздничных",
        "total_sick" to "Больничных",
        "total_vacation" to "Отпускных",
        "shared_off" to "Общих выходных",
        "find_star" to "✦ — день, когда у всех выбранных графиков выходной",
        "no_shared" to "Общих выходных в этом месяце нет",
        "try_other" to "Попробуйте другой месяц или другие графики",
        "all_working" to "Все на работе",
        "edit_day" to "День",
        "schedule_label" to "График",
        "shift_type" to "Тип смены",
        "duration" to "Длительность",
        "days_n" to "%d дн.",
        "after_period" to "После окончания:",
        "continue_pattern" to "Дальше как по графику",
        "shift_cycle" to "Сдвинуть цикл на %d дн.",
        "apply_to" to "Применить к",
        "this_day" to "Только этот день",
        "this_following" to "Этот и последующие",
        "entire_schedule" to "Весь график с начала",
        "clear_day" to "Очистить день (вернуть к шаблону)",
        "save" to "Сохранить",
        "cancel" to "Отмена",
        "new_schedule" to "Новый график",
        "edit_schedule" to "Редактировать график",
        "name_label" to "Название",
        "placeholder_name" to "Я, Жена, Петя…",
        "name_error" to "Имя не может состоять из пробелов",
        "color" to "Цвет",
        "template" to "Шаблон",
        "no_template" to "Без шаблона (ручной)",
        "start_date" to "Дата начала",
        "create" to "Создать",
        "new_template" to "Новый шаблон",
        "edit_template" to "Редактировать шаблон",
        "built_in_edit_hint" to "Встроенный шаблон не изменяется. Будет создана ваша копия.",
        "preview" to "Предпросмотр",
        "description" to "Описание",
        "add_shifts" to "Добавить смены:",
        "sequence" to "Последовательность (нажатие убирает):",
        "empty_pattern" to "Пусто — добавьте смены кнопками выше",
        "templates_title" to "Графики и шаблоны",
        "templates_subtitle" to "Создавайте цикл один раз — календарь повторит его за вас",
        "search_placeholder" to "Поиск…",
        "search" to "Поиск",
        "clear" to "Очистить",
        "my_schedules" to "Мои графики",
        "built_in" to "Встроенные шаблоны",
        "user_templates" to "Пользовательские шаблоны",
        "no_schedules_yet" to "Нет графиков",
        "create_first" to "Создайте первый график — по шаблону или вручную",
        "no_templates_yet" to "Нет пользовательских шаблонов",
        "search_no_results" to "Ничего не найдено",
        "search_try_again" to "Измените запрос или очистите поиск",
        "invalid_date" to "дата не задана",
        "create_template" to "Соберите свою последовательность смен",
        "manual" to "Ручной",
        "from" to "с",
        "copy" to "Копировать",
        "copy_suffix" to " (копия)",
        "edit" to "Редактировать",
        "delete" to "Удалить",
        "copy_created" to "Копия создана",
        "undo" to "Отменить",
        "deleted_schedule" to "График «%s» удалён",
        "delete_schedule_q" to "Удалить график?",
        "delete_schedule_text" to "«%s» будет удалён. Сразу после этого можно отменить.",
        "delete_template_q" to "Удалить шаблон?",
        "template_used" to "Используется в графиках: %d. Они станут ручными.",
        "template_deleted_text" to "Шаблон будет удалён.",
        "compare_subtitle" to "Найдите общие дни, ночи и выходные выбранных графиков",
        "schedules" to "Графики",
        "selected_count" to "выбрано",
        "shared_off_found" to "Нашли общие выходные",
        "days_this_month" to "дней в этом месяце",
        "select_two_schedules" to "Выберите минимум два графика",
        "shared_day" to "Общий день",
        "shared_night" to "Общая ночь",
        "shared_day_short" to "День",
        "shared_night_short" to "Ночь",
        "shared_short" to "Общий выходной",
        "compare_read_title" to "Как читать календарь",
        "compare_day_hint" to "Зелёный контур — все выбранные графики работают днём; сутки тоже учитываются.",
        "compare_night_hint" to "Фиолетовый контур — все выбранные графики работают ночью; сутки тоже учитываются.",
        "compare_off_hint" to "Жёлтый контур — у всех выбранных графиков выходной.",
        "compare_24_hint" to "Сутки остаются оранжевыми: зелёный контур — совпадение с днём, фиолетовый — с ночью.",
        "shared_day_desc" to "все выбранные графики работают днём, включая сутки",
        "shared_night_desc" to "все выбранные графики работают ночью, включая сутки",
        "day_night_not_match" to "День и ночь между графиками не считаются одним совпадением.",
        "total_work" to "Рабочих смен",
        "total_24" to "Суток",
        "day_short" to "День",
        "night_short" to "Ночь",
        "off_short" to "Выход",
        "prev_year" to "Предыдущий год",
        "next_year" to "Следующий год",
        "holiday_legend" to "Официальный праздничный день РФ",
        "twenty_four" to "Сутки",
        "twenty_four_desc" to "Смена длительностью 24 часа; в совпадениях может сочетаться и с днём, и с ночью.",
        "settings_subtitle" to "Настройте внешний вид, уведомления и данные",
        "appearance" to "Внешний вид",
        "shifts_and_colors" to "Смены и цвета",
        "colors_hint" to "Яркие цвета показывают тип смены даже без эмодзи.",
        "notification_permission_denied" to "Разрешение на уведомления не выдано",
        "notifications_blocked" to "Android заблокировал уведомления для приложения.",
        "open_notification_settings" to "Открыть настройки уведомлений",
        "time_invalid" to "Введите время от 00:00 до 23:59.",
        "next_shift_not_found" to "Следующая рабочая смена не найдена",
        "month_summary" to "Итоги месяца",
        "work_shifts" to "рабочих смен",
        "off_days_short" to "выходных",
        "active" to "Активен",
        "edit_day_subtitle" to "Измените смену только для выбранных графиков.",
        "onb_hero" to "Смены — на одном экране.",
        "onb_intro" to "Задайте цикл один раз — приложение заполнит календарь и поможет сравнивать графики.",
        "onb_preview_month" to "Ваш календарь",
        "onb_preview_sub" to "Цвет показывает тип смены · день, ночь и выходной",
        "template_example" to "Например: 2 день → 2 ночь → 2 выходных.",
        "rhythm" to "Ритм",
        "built_in_label" to "Встроенный",
        "use" to "Использовать",
        "schedule_create_hint" to "Выберите готовый ритм или оставьте ручной режим.",
        "schedule_edit_hint" to "Изменения сохраняются только для этого графика.",
        "schedule_name_placeholder" to "Например: Основная работа",
        "schedule_color" to "Цвет графика",
        "shift_rhythm" to "Ритм смен",
        "manual_default" to "Без шаблона — смены меняются вручную.",
        "select" to "Выбрать",
        "create_schedule" to "Создать график",
        "compare_title" to "Совпадения",
        "month_view" to "Месяц",
        "year_view" to "Год",
        "no_schedules" to "Нет графиков",
        "create_one" to "Создайте хотя бы один график в календаре",
        "stats" to "Статистика",
        "estimated_salary" to "Примерный доход",
        "total_off" to "Выходных",
        "total_day" to "Дневных",
        "total_night" to "Ночных",
        "year_total" to "Итог за %d",
        "year_by_schedule" to "По графикам за год",
        "appearance_theme" to "Тема",
        "theme_system" to "Системная",
        "theme_dark" to "Тёмная",
        "theme_light" to "Светлая",
        "theme_sepia" to "Сепия",
        "theme_midnight" to "Полночь",
        "theme_ocean" to "Океан",
        "theme_forest" to "Лес",
        "theme_berry" to "Ягода",
        "notifications" to "Уведомления",
        "notification_title" to "Смены завтра",
        "notification_shared_off" to "✦ Завтра общий выходной!",
        "reminders" to "Напоминания",
        "reminders_desc" to "Сводка смен на завтра",
        "time_dialog_title" to "Время напоминания",
        "time_dialog_hint" to "Часы и минуты",
        "time_label" to "Время (ЧЧ:ММ)",
        "change_time" to "Изменить время",
        "display" to "Отображение",
        "emoji" to "Эмодзи в клетках",
        "emoji_desc" to "Без эмодзи тип смены определяется по цвету",
        "week_start" to "Первый день недели",
        "mon" to "Понедельник",
        "sun" to "Воскресенье",
        "data" to "Данные",
        "data_desc" to "Резервная копия графиков и шаблонов в файл JSON",
        "version" to "Версия %s · данные хранятся на устройстве",
        "export" to "Экспорт",
        "import" to "Импорт",
        "exported" to "Данные экспортированы",
        "export_error" to "Ошибка экспорта",
        "imported" to "Импорт выполнен",
        "import_bad" to "Файл не подходит",
        "import_error" to "Ошибка импорта",
        "settings_controls_title" to "Управление",
        "settings_controls_desc" to "Календарь: нажатие — изменить смену, долгое нажатие — кто где, свайп или стрелки — месяц. Шаблоны: удержание — сортировка, свайп влево — удалить. Совпадения: нажатие на день — подробности.",
        "app_info_title" to "О приложении",
        "app_info_desc" to "ShiftWeave — планировщик рабочих смен. Несколько графиков, шаблоны, сравнение, праздники РФ, Material You, виджет и бэкапы в JSON. Все данные на устройстве.",
        "app_license" to "Работает без интернета · данные хранятся локально",
        "onb_title" to "Добро пожаловать",
        "onb_sub" to "График работы",
        "onb1" to "Создайте первый график",
        "onb1d" to "Выберите готовый шаблон или соберите собственный цикл вручную. Дальше календарь заполнит смены автоматически.",
        "onb2" to "Сравнивайте графики",
        "onb2d" to "Выберите несколько графиков и сразу увидите общие дни, ночи и выходные.",
        "onb3" to "Получайте напоминания",
        "onb3d" to "Получайте сводку смен на завтра в выбранное время.",
        "onb_btn" to "Создать первый график",
        "onb_note" to "Все данные хранятся на вашем устройстве",
        "widget_title" to "Смены",
        "widget_today" to "Сегодня",
        "widget_tomorrow" to "Завтра",
        "theme_dynamic" to "Как в системе",
        "lang_title" to "Язык",
        "lang_system" to "Системный",
        "lang_ru" to "Русский",
        "lang_en" to "Английский",
        "rf_holidays_title" to "Праздники РФ",
        "rf_holidays_desc" to "Отмечать официальные государственные праздники в календаре",
        "rf_holidays" to "Праздники РФ",
        "holidays_salary" to "Праздники",
        "salary_desc" to "Подсвечивать официальные праздничные дни в календаре.",
        "rate_label" to "Ставка, ₽/час",
        "day_hours" to "День, ч",
        "night_hours" to "Ночь, ч",
        "salary_line" to "≈ %d ₽ за месяц",
        "theme_sand" to "Песок",
        "theme_plum" to "Слива",
        "theme_graphite" to "Графит",
        "ctrl_tap" to "Нажатие на день — поставить или изменить смену",
        "ctrl_long" to "Долгое нажатие — кто где в этот день",
        "ctrl_swipe" to "Свайп или стрелки — смена месяца",
        "ctrl_drag" to "В шаблонах: зажать и тянуть — сортировка, свайп влево — удаление",
        "ctrl_copy" to "Кнопка с двумя квадратами — копия графика или шаблона",
        "ctrl_compare" to "В сравнении: тап по дню — кто где",
        "about_1" to "Несколько графиков и собственные шаблоны смен",
        "about_2" to "Сравнение графиков и поиск общих выходных",
        "about_3" to "Статистика по месяцам",
        "about_4" to "Виджет на рабочем столе и резервные копии в JSON",
        "about_5" to "Все данные хранятся только на вашем устройстве",
        "version_footer" to "ShiftWeave · v%s · данные хранятся на устройстве",
        "hide_tip" to "Скрыть подсказку"
    )

    private val en = mapOf(
        "tab_calendar" to "Calendar",
        "tab_templates" to "Templates",
        "tab_compare" to "Matches",
        "tab_settings" to "Settings",
        "today" to "Today",
        "today_label" to "Today",
        "next_shift" to "Next shift",
        "no_shift" to "no shift",
        "hint_calendar" to "Swipe or ‹ › — month · tap — edit · long press — who is where",
        "tip_calendar" to "Tap a day — set shift. Long press — who is where. Swipe/arrows — month. 🎉 — RU holidays highlighted automatically.",
        "tip_templates" to "Long press and drag — reorder. Swipe left — delete. Copy button — duplicate schedule.",
        "tip_compare" to "Fill shows shift types. Outline shows a match: green — day, purple — night, yellow — shared day off. A 24-hour shift can match both.",
        "tip_settings" to "Dark/light/system theme, RU/EN language, RU holidays, notifications and JSON backup.",
        "add_schedule" to "Add schedule",
        "select_schedule" to "Select schedule",
        "who_where" to "Who is where",
        "close" to "Close",
        "prev_month" to "Previous month",
        "next_month" to "Next month",
        "day_shifts" to "Day",
        "night_shifts" to "Night",
        "off_days" to "Off",
        "total_holiday" to "Holidays",
        "total_sick" to "Sick leaves",
        "total_vacation" to "Vacations",
        "shared_off" to "Shared days off",
        "find_star" to "✦ — a day when all selected schedules are off",
        "no_shared" to "No shared days off this month",
        "try_other" to "Try another month or other schedules",
        "all_working" to "All working",
        "edit_day" to "Day",
        "schedule_label" to "Schedule",
        "shift_type" to "Shift type",
        "duration" to "Duration",
        "days_n" to "%d d.",
        "after_period" to "After period:",
        "continue_pattern" to "Continue with pattern",
        "shift_cycle" to "Shift cycle by %d days",
        "apply_to" to "Apply to",
        "this_day" to "This day only",
        "this_following" to "This day and following",
        "entire_schedule" to "Entire schedule from the start",
        "clear_day" to "Clear day (return to template)",
        "save" to "Save",
        "cancel" to "Cancel",
        "new_schedule" to "New schedule",
        "edit_schedule" to "Edit schedule",
        "name_label" to "Name",
        "placeholder_name" to "Me, Wife, Pete…",
        "name_error" to "Name can't be only spaces",
        "color" to "Color",
        "template" to "Template",
        "no_template" to "No template (manual)",
        "start_date" to "Start date",
        "create" to "Create",
        "new_template" to "New template",
        "edit_template" to "Edit template",
        "built_in_edit_hint" to "Built-in templates stay unchanged. Your copy will be created.",
        "preview" to "Preview",
        "description" to "Description",
        "add_shifts" to "Add shifts:",
        "sequence" to "Sequence (tap to remove):",
        "empty_pattern" to "Empty — add shifts with buttons above",
        "templates_title" to "Schedules & Templates",
        "templates_subtitle" to "Build a cycle once and let the calendar repeat it",
        "search_placeholder" to "Search…",
        "search" to "Search",
        "clear" to "Clear",
        "my_schedules" to "My schedules",
        "built_in" to "Built-in templates",
        "user_templates" to "User templates",
        "no_schedules_yet" to "No schedules",
        "create_first" to "Create your first schedule — by template or manually",
        "no_templates_yet" to "No user templates",
        "search_no_results" to "Nothing found",
        "search_try_again" to "Change the query or clear search",
        "invalid_date" to "date unavailable",
        "create_template" to "Build your own shift sequence",
        "manual" to "Manual",
        "from" to "from",
        "copy" to "Copy",
        "copy_suffix" to " (copy)",
        "edit" to "Edit",
        "delete" to "Delete",
        "copy_created" to "Copy created",
        "undo" to "Undo",
        "deleted_schedule" to "Schedule “%s” deleted",
        "delete_schedule_q" to "Delete schedule?",
        "delete_schedule_text" to "“%s” will be deleted. You can undo right after.",
        "delete_template_q" to "Delete template?",
        "template_used" to "Used by %d schedules. They will become manual.",
        "template_deleted_text" to "Template will be deleted.",
        "compare_subtitle" to "Find shared day, night and day-off dates across schedules",
        "schedules" to "Schedules",
        "selected_count" to "selected",
        "shared_off_found" to "Shared days off found",
        "days_this_month" to "days this month",
        "select_two_schedules" to "Select at least two schedules",
        "shared_day" to "Shared day",
        "shared_night" to "Shared night",
        "shared_day_short" to "Day",
        "shared_night_short" to "Night",
        "shared_short" to "Shared day off",
        "compare_read_title" to "How to read the calendar",
        "compare_day_hint" to "Green outline — all selected schedules work during the day; 24-hour shifts count too.",
        "compare_night_hint" to "Purple outline — all selected schedules work at night; 24-hour shifts count too.",
        "compare_off_hint" to "Yellow outline — all selected schedules are off.",
        "compare_24_hint" to "24-hour shifts stay orange: green outline = matches day, purple = matches night.",
        "shared_day_desc" to "all selected schedules work during the day, including 24-hour shifts",
        "shared_night_desc" to "all selected schedules work at night, including 24-hour shifts",
        "day_night_not_match" to "Day and night work are not treated as the same match.",
        "total_work" to "Work shifts",
        "total_24" to "24-hour shifts",
        "day_short" to "Day",
        "night_short" to "Night",
        "off_short" to "Off",
        "prev_year" to "Previous year",
        "next_year" to "Next year",
        "holiday_legend" to "Official public holiday in Russia",
        "twenty_four" to "24 hours",
        "twenty_four_desc" to "A 24-hour shift; it matches both day and night work.",
        "settings_subtitle" to "Configure appearance, notifications and data",
        "appearance" to "Appearance",
        "shifts_and_colors" to "Shifts and colors",
        "colors_hint" to "Bright colors keep shift types clear even without emoji.",
        "notification_permission_denied" to "Notification permission was not granted",
        "notifications_blocked" to "Android has blocked notifications for this app.",
        "open_notification_settings" to "Open notification settings",
        "time_invalid" to "Enter a time from 00:00 to 23:59.",
        "next_shift_not_found" to "No upcoming work shift found",
        "month_summary" to "Month summary",
        "work_shifts" to "work shifts",
        "off_days_short" to "days off",
        "active" to "Active",
        "edit_day_subtitle" to "Change the shift only for the selected schedules.",
        "onb_hero" to "Your shifts — one clear calendar.",
        "onb_intro" to "Set your cycle once — the app fills your calendar and helps you compare schedules.",
        "onb_preview_month" to "Your calendar",
        "onb_preview_sub" to "Color shows the shift type · day, night and day off",
        "template_example" to "Example: 2 day → 2 night → 2 days off.",
        "rhythm" to "Rhythm",
        "built_in_label" to "Built-in",
        "use" to "Use",
        "schedule_create_hint" to "Choose a ready-made rhythm or keep manual mode.",
        "schedule_edit_hint" to "Changes apply only to this schedule.",
        "schedule_name_placeholder" to "For example: Main job",
        "schedule_color" to "Schedule color",
        "shift_rhythm" to "Shift rhythm",
        "manual_default" to "No template — shifts are changed manually.",
        "select" to "Select",
        "create_schedule" to "Create schedule",
        "compare_title" to "Matches",
        "month_view" to "Month",
        "year_view" to "Year",
        "no_schedules" to "No schedules",
        "create_one" to "Create at least one schedule in calendar",
        "stats" to "Statistics",
        "estimated_salary" to "Estimated pay",
        "total_off" to "Days off",
        "total_day" to "Day shifts",
        "total_night" to "Night shifts",
        "year_total" to "Total for %d",
        "year_by_schedule" to "By schedule for the year",
        "appearance_theme" to "Theme",
        "theme_system" to "System",
        "theme_dark" to "Dark",
        "theme_light" to "Light",
        "theme_sepia" to "Sepia",
        "theme_midnight" to "Midnight",
        "theme_ocean" to "Ocean",
        "theme_forest" to "Forest",
        "theme_berry" to "Berry",
        "notifications" to "Notifications",
        "notification_title" to "Shifts tomorrow",
        "notification_shared_off" to "✦ Shared day off tomorrow!",
        "reminders" to "Reminders",
        "reminders_desc" to "Shift summary for tomorrow",
        "time_dialog_title" to "Reminder time",
        "time_dialog_hint" to "Hours and minutes",
        "time_label" to "Time (HH:MM)",
        "change_time" to "Change time",
        "display" to "Display",
        "emoji" to "Emoji in cells",
        "emoji_desc" to "Without emoji, the shift type is shown by color",
        "week_start" to "First day of week",
        "mon" to "Monday",
        "sun" to "Sunday",
        "data" to "Data",
        "data_desc" to "Backup of schedules and templates to a JSON file",
        "version" to "Version %s · data stays on your device",
        "export" to "Export",
        "import" to "Import",
        "exported" to "Data exported",
        "export_error" to "Export failed",
        "imported" to "Import completed",
        "import_bad" to "Unsupported file",
        "import_error" to "Import failed",
        "settings_controls_title" to "Controls",
        "settings_controls_desc" to "Calendar: tap — change a shift, long press — who is where, swipe or arrows — month. Templates: hold — reorder, swipe left — delete. Matches: tap a day — details.",
        "app_info_title" to "About",
        "app_info_desc" to "ShiftWeave — shift planner. Multiple schedules, templates, comparison, RU holidays, Material You, widget, JSON backups. All data stays on device.",
        "version_footer" to "ShiftWeave · v%s · data stays on your device",
        "hide_tip" to "Hide tip",
        "app_license" to "Works offline · data stays on device",
        "onb_title" to "Welcome",
        "onb_sub" to "ShiftWeave",
        "onb1" to "Create your first schedule",
        "onb1d" to "Pick a ready-made template or build your own cycle manually. The calendar fills the shifts automatically.",
        "onb2" to "Add your family",
        "onb2d" to "Spouse or partner schedules to find shared days off",
        "onb3" to "Get reminders",
        "onb3d" to "Get a summary of tomorrow’s shifts at the selected time.",
        "onb_btn" to "Create first schedule",
        "onb_note" to "All data stays on your device",
        "widget_title" to "Shifts",
        "widget_today" to "Today",
        "widget_tomorrow" to "Tomorrow",
        "theme_dynamic" to "System (Material You)",
        "lang_title" to "Language",
        "lang_system" to "System",
        "lang_ru" to "Russian",
        "lang_en" to "English",
        "rf_holidays_title" to "Russian holidays",
        "rf_holidays_desc" to "Highlight official holidays in the calendar",
        "rf_holidays" to "RU holidays",
        "holidays_salary" to "Holidays",
        "salary_desc" to "Highlight official holidays in the calendar.",
        "rate_label" to "Rate, ₽/h",
        "day_hours" to "Day, h",
        "night_hours" to "Night, h",
        "salary_line" to "≈ %d ₽ this month",
        "theme_sand" to "Sand",
        "theme_plum" to "Plum",
        "theme_graphite" to "Graphite",
        "ctrl_tap" to "Tap a day — set or change a shift",
        "ctrl_long" to "Long press — who is where that day",
        "ctrl_swipe" to "Swipe or arrows — change month",
        "ctrl_drag" to "Templates: press and drag — reorder, swipe left — delete",
        "ctrl_copy" to "Two-squares button — duplicate schedule or template",
        "ctrl_compare" to "Compare: tap a day — who is where",
        "about_1" to "Multiple schedules and custom shift templates",
        "about_2" to "Schedule comparison and shared days off",
        "about_3" to "Monthly statistics",
        "about_4" to "Home screen widget and JSON backups",
        "about_5" to "All data stays on your device"
    )

    fun getSystemLanguage(): String {
        val lang = Locale.getDefault().language
        return if (lang in listOf("ru", "kk", "uk", "be")) "ru" else "en"
    }

    fun raw(lang: String, key: String): String {
        return if (lang == "en") en[key] ?: ru[key] ?: key else ru[key] ?: key
    }
}

@Composable
fun monthLocale(): Locale {
    return if (LocalLang.current == "en") Locale.ENGLISH else Locale("ru")
}

@Composable
fun tr(key: String, vararg args: Any): String {
    val s = Strings.raw(LocalLang.current, key)
    return if (args.isEmpty()) s else s.format(*args)
}








